name: Build-Release-Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: KzLibraries.sln
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build
        run: dotnet build ${{ env.WORKFLOW_BUILD_SLN }} -c Release
      - name: Test
        run: dotnet test ${{ env.WORKFLOW_BUILD_SLN }} --no-build --logger GitHubActions -c Release
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: bin/Packages/Release

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "VERSION_TAG=${GITHUB_REF##*/v}" >> $GITHUB_ENV
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Upload nuget
        run: dotnet nuget push "./dist/*.nupkg" --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
      - name: Create release
        uses: ncipollo/release-action@v1
        id: create-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.VERSION_TAG }}
          name: Version ${{ env.VERSION_TAG }}
          # body: https://github.com/${{ github.repository }}/blob/${{ env.TAG }}/CHANGELOG.md
          artifacts: "./dist/*.nupkg,./dist/*.snupkg"